### ISSUE TITLE
Conflict w/SteamDB extension

### ISSUE THREAD

**Issue by Fan4eGGG** [IsThereAnyDeal/AugmentedSteam#1692]
the steamDB extension has a function of outputting buttons for pcgaming and steamdb with links, next to the Community Hub button. after yesterdays update of AS these buttons became very small and impossible to hit.
here is when AS is on [CLICK](https://prnt.sc/Vza7AUt623V7), and here is when it is off [CLICK](https://prnt.sc/b9ikJ2DYzevp).

**Comment by xPaw** [comment]
SteamDB's images get hidden by this css in AS:
```
.apphub_OtherSiteInfo:not(.loading) img:not(.es-in-wl) {
    display: none;
}
```

**Comment by Fan4eGGG** [comment]
and what am I supposed to do with it?
I dont know anything about it.

**Comment by Fan4eGGG** [comment]
@xPaw pls halp :(
I dont understand how to fix the problem, Im a nerd about all this..

**Comment by candela97** [comment]
We're planning a patch release after the current version clears AMO review. In the mean time, you can add this style using a userstyle manager like Stylus to fix it
```css
.btn_steamdb img {
  display: inline !important;
}
```

**Comment by woctezuma** [comment]
It would be nice if there was [a release](https://github.com/IsThereAnyDeal/AugmentedSteam/releases) with this fix.

**Comment by sheppard-tr** [comment]
@candela97 When will this issue be fixed? It is very annoying and I usually use those buttons.

**Comment by lainverse** [comment]
@sheppard-tr As I understand it's already fixed. The just have to make a release with this fix... and it looks like they working on something bigger for now.
For now I can suggest to install Stylus extension:
* Chrome https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne
* Firefox https://addons.mozilla.org/en-US/firefox/addon/styl-us/
And add following style into it:
``` CSS
@-moz-document domain("store.steampowered.com"), domain("steamcommunity.com") {
.btn_steamdb img {
  display: inline !important;
}
}
```
