### ISSUE TITLE
[FEATURE REQUEST] Option to see warning about games with AI generated content

### ISSUE THREAD

**Issue by kazerniel** [IsThereAnyDeal/AugmentedSteam#1913]
### Current Behavior (if any)
\-

### Desired Behavior
basically same as the DRM warning

### Motivation / Use Case for Changing the Behavior
I want to avoid games with such content, but that "AI Generated Content Disclosure" that Steam obligates developers to use is tucked away at the bottom of the game's description. It would be helpful to have its presence/content be much more attention-grabbing.

**Comment by candela97** [comment]
Do you have an example of such a game?

**Comment by kazerniel** [comment]
Came across this one today: https://store.steampowered.com/app/2847640/A_Living_Room/

**Comment by candela97** [comment]
So this is gonna be tricky. There're other content descriptor sections as well (e.g. adult) and apart from the text there's nothing to tell them apart. We can match the text, but it'll likely get localized and some point.

**Comment by Tenome** [comment]
Can this be reviewed again? Steam has a separate AI disclaimer under its own header now (`AI Generated Content Disclosure.`) If that's detected, show a little warning (like how Denuvo/DRM gets a red banner).

**Comment by kazerniel** [comment]
> Steam has a separate AI disclaimer under its own header now (AI Generated Content Disclosure.)

That had already been introduced by the time I raised the ticket 🙂

What I ended up doing in my browser is to give the warning a vivid red background with [Stylus](https://addons.mozilla.org/en-GB/firefox/addon/styl-us/). I still have to scroll down to see it, but at least it pokes me in the eye when I do.

```css
div#game_area_content_descriptors:has(span.ai-warning)
{
	background: #800;
	padding: 0 8px;
}
```

**Comment by kazerniel** [comment]
I came up with a way to push the AI warning box on the top of that left column. Currently this is the full code:

```css
#game_area_content_descriptors:has(span.ai-warning)
{
	background: #800;
	margin: 0 0 2em 0;
	padding: 0 8px;
}

.leftcol.game_description_column
{
	display: flex;
	flex-direction: column;
}

.leftcol.game_description_column .game_page_autocollapse_ctn:has(.ai-warning)
{
	order: 1;
}

.leftcol.game_description_column > *:not(:has(.ai-warning))
{
	order: 2;
}
```
